name: Push to RubyGems

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.0' 
      - name: Install dependencies
        run: bundle install
      - name: Build gem
        run: gem build GEM_NAME.gemspec
      - name: Publish to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push GEM_NAME-*.gem
