name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.6.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.1

    - name: Build the gem
      run: gem build *.gemspec

    - name: Publish to GitHub Packages
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
      run: |
        mkdir -p $HOME/.gem
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        gem push --key github --host https://rubygems.pkg.github.com/${OWNER} *.gem

    - name: Publish to RubyGems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir -p $HOME/.gem
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        gem push *.gem
