name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0



    - name: Check Ruby version
      run: ruby --version

    - name: Check gem version
      run: gem --version

    - name: Install Bundler with verbose output
      run: gem install bundler --no-document --verbose

    - name: Verify Bundler installation
      run: bundler --version

    - name: Build the gem
      run: gem build *.gemspec

    - name: Push to RubyGems
      run: gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
