name: Build + Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ruby-version: ['2.7.8', '3.2.2']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec

    - name: Build and publish
      run: gem build rubber-ducky.gemspec && gem push rubber-ducky-*.gem
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
